/**
 * `sync/` — the local-first replica (M1.2) and, from M1.3, the sync engine and outbox.
 *
 * M1.2 surface: the Dexie schema + row types (`db`), the canonical query-key serialization
 * (`query-key`), the account-scoped repository (`repo`), and the React liveQuery binding
 * (`react`). The sync engine (delta fetch, push integration, outbox replay) lands in M1.3.
 */

export {
  type BlobDownload,
  type BlobRef,
  getOrFetchBlob,
  MAX_CACHED_BLOB_BYTES,
} from './blob-cache'
export {
  type CacheCategory,
  type CacheUsage,
  collectCacheUsage,
} from './cache-usage'
export {
  type AccountRecord,
  type AddressBookRow,
  type AddressStatRow,
  BLOB_META_OVERHEAD_BYTES,
  type BlobMetaRow,
  BODY_OVERHEAD_BYTES,
  type CalendarEventRow,
  type CalendarQueryCacheRow,
  type CalendarRow,
  type ConflictCode,
  type ContactCardRow,
  type ContactQueryCacheRow,
  clearAccount,
  collectBodyBlobIds,
  currentReplicaName,
  type DraftAttachmentLike,
  type DraftRow,
  type DraftSyncStatus,
  type EmailBodyRow,
  type EmailEnvelopeInput,
  type EmailRow,
  ENVELOPE_BYTES_ESTIMATE,
  estimateBlobBytes,
  estimateBodyBytes,
  FILE_TREE_STATE_KEY,
  type FileNodeRow,
  type FileTreeState,
  getReplica,
  type IdentityRow,
  isEphemeralReplica,
  type LocalPrefRow,
  type MailboxRow,
  type OutboxConflict,
  type OutboxRow,
  type OutboxStatus,
  type OutboxUndo,
  type QueryCacheRow,
  REPLICA_DB_NAME,
  ReplicaDb,
  resetReplica,
  resetReplicaForTests,
  type SerializedDraft,
  type SyncStateRow,
  scopeKey,
  setReplicaName,
  type ThreadRow,
  toAddressBookRow,
  toCalendarEventRow,
  toCalendarRow,
  toContactCardRow,
  toEmailRow,
  toFileNodeRow,
  toIdentityRow,
  toMailboxRow,
  toThreadRow,
  wipeReplica,
} from './db'
export {
  dispatchOrReport,
  getDispatchFailureAt,
  getDispatchFailureMessage,
  reportDispatchFailure,
  resetDispatchFailure,
  subscribeDispatchFailure,
} from './dispatch-failure'
export {
  EPHEMERAL_DB_PREFIX,
  EPHEMERAL_INDEX_KEY,
  newEphemeralDbName,
  releaseEphemeralClaim,
  sweepEphemeral,
} from './ephemeral'
export {
  canonicalCalendarQueryKey,
  canonicalContactQueryKey,
  canonicalQueryKey,
  type QuerySpec,
} from './query-key'
export {
  type CalendarWindow,
  getActiveReplica,
  type ReplicaContextValue,
  ReplicaProvider,
  type ReplicaProviderProps,
  useAddressBooks,
  useAddressBooksFor,
  useAllFileNodes,
  useCalendars,
  useCalendarWindow,
  useContactCard,
  useContactCardResolved,
  useContactCards,
  useContactWindow,
  useEmail,
  useEmailBody,
  useEmailWindow,
  useFileNodes,
  useFileTreeState,
  useIdentities,
  useLocalPref,
  useLocalPrefOptional,
  useMailbox,
  useMailboxByRole,
  useMailboxByRoleOptional,
  useMailboxes,
  useMailboxesFor,
  useMailboxOptional,
  useQueryWindow,
  useReplica,
  useReplicaOptional,
  useReplicaQuery,
  useThread,
} from './react'
export * from './repo'
export {
  browserEstimate,
  type EstimateFn,
  getStorageFullAt,
  isPersisted,
  isQuotaExceeded,
  reportStorageFull,
  requestPersistence,
  resetStorageFull,
  type StorageEstimateLike,
  subscribeStorageFull,
} from './storage'
